"""Publish the schedule to the Obsidian vault as a generated markdown note.

Runs daily from Task Scheduler. The vault note is an output, never an input:
the app does not read it, and a failure here affects nothing else.
"""
import datetime
import sys
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).parent))
from couch import CouchDB, CouchError, load_env  # noqa: E402
from obsidian import Obsidian, ObsidianAuthError, ObsidianError  # noqa: E402
from sync_calendar import read_day_docs  # noqa: E402
from vault_render import GENERATED_MARKER, comparable, render  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_API = "http://127.0.0.1:27123"
DEFAULT_NOTE = "Schedule.md"
DAYS = 7


def decide(existing, rendered):
    """Return (action, reason) for what to do with the target note.

    Refusing to overwrite an ungenerated file is the guard against the day a
    human writes a real note at this path. Skipping when only the timestamp
    differs is what stops a daily rewrite that carries no information.
    """
    if existing is None or not existing.strip():
        return "write", "the note does not exist yet"
    if GENERATED_MARKER not in existing:
        return "refuse", (
            "the existing note is not generated by this script. Refusing to "
            "overwrite it. Move it aside first if it should be replaced."
        )
    if comparable(existing) == comparable(rendered):
        return "skip", "content is unchanged"
    return "write", "content changed"


def read_todos(couch, db_name):
    """Fetch every todo document. The archive is kept forever, but it is one
    small document per item and the renderer filters to the recent window."""
    status, body = couch.request(
        "GET", f"/{db_name}/_all_docs?startkey=%22todo%3A%22&endkey=%22todo%3A%EF%BF%B0%22&include_docs=true",
    )
    if status != 200:
        raise CouchError(status, body)
    return [row["doc"] for row in body.get("rows", []) if row.get("doc")]


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    env = load_env(ROOT / ".env")

    token = env.get("OBSIDIAN_API_KEY")
    if not token:
        print("AUTH FAILURE: OBSIDIAN_API_KEY is missing from schedule-app/.env")
        return 2

    timezone = env.get("SCHEDULE_TIMEZONE", "Asia/Manila")
    note_path = env.get("OBSIDIAN_NOTE_PATH", DEFAULT_NOTE)
    api_url = env.get("OBSIDIAN_API_URL", DEFAULT_API)
    db_name = env.get("COUCHDB_DB", "schedule")

    couch = CouchDB(env["COUCHDB_URL"], env["COUCHDB_USER"], env["COUCHDB_PASSWORD"])
    template = couch.get_doc(db_name, "schedule:v1")
    if template is None:
        print("no schedule:v1 document. Run scripts/seed.py first.")
        return 1

    now = datetime.datetime.now(ZoneInfo(timezone))
    start_date = now.date()
    day_docs = read_day_docs(couch, db_name, start_date, DAYS)
    todos = read_todos(couch, db_name)
    rendered = render(template, day_docs, start_date, now, todos=todos)

    api = Obsidian(api_url, token)
    existing = api.read(note_path)
    action, reason = decide(existing, rendered)

    if action == "refuse":
        print(f"REFUSED: {note_path}: {reason}")
        return 3
    if action == "skip":
        print(f"{note_path}: unchanged, not written")
        return 0

    api.write(note_path, rendered)
    print(f"{note_path}: written ({reason}, {len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ObsidianAuthError as exc:
        # Distinct exit code: a retry can never fix a rejected key.
        print(f"AUTH FAILURE: {exc}")
        raise SystemExit(2)
    except (ObsidianError, CouchError) as exc:
        print(f"TRANSIENT FAILURE: {exc}")
        raise SystemExit(1)
