"""Render the schedule as a markdown note. Pure: no I/O lives here.

Keeping the rendering separate from the CouchDB read and the Obsidian write is
what makes the interesting behaviour testable without a network, the same split
that made the calendar planning logic testable.
"""
import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from calendar_plan import DOW, blocks_for, resolve_blocks  # noqa: E402

GENERATED_MARKER = "> Generated by scripts/export_to_vault.py. Do not edit by hand."
_STAMP_PREFIX = "> Last rendered:"

FULL_NAME = {
    "mon": "Monday", "tue": "Tuesday", "wed": "Wednesday", "thu": "Thursday",
    "fri": "Friday", "sat": "Saturday", "sun": "Sunday",
}
SHORT_NAME = {
    "mon": "Mon", "tue": "Tue", "wed": "Wed", "thu": "Thu",
    "fri": "Fri", "sat": "Sat", "sun": "Sun",
}


def _block_line(block):
    """One block as a list item. ASCII only, so the console never chokes."""
    line = f"- `{block['start']}-{block['end']}` **{block['label']}**"
    detail = (block.get("detail") or "").strip()
    return f"{line} - {detail}" if detail else line


def _template_section(template):
    lines = ["## Template", ""]
    for dow in DOW:
        day = template["days"][dow]
        lines.append(f"### {FULL_NAME[dow]}")
        lines.append("")
        if day.get("branching"):
            for branch in ("A", "B"):
                lines.append(f"#### Branch {branch}")
                lines.append("")
                lines.extend(_block_line(b) for b in day["branches"][branch])
                lines.append("")
        else:
            lines.extend(_block_line(b) for b in day["blocks"])
            lines.append("")
    return lines


def _to_minutes(hhmm):
    hours, minutes = hhmm.split(":")
    return int(hours) * 60 + int(minutes)


def render_override_line(day, defaults):
    """One line naming only the overridden halves of the night, or "" if clean.

    Clean days render nothing on purpose. The export's acceptance test is that
    a second run reports "unchanged, not written", and a line that always
    rendered would carry no information while making every nudged night
    indistinguishable in a vault diff from a template change.
    """
    parts = []
    for name, field in (("sleep", "sleepOverride"), ("wake", "wakeOverride")):
        value = day.get(field)
        if not value:
            continue
        delta = _to_minutes(value) - _to_minutes(defaults[name])
        parts.append("{} {} ({:+d})".format(name, value, delta))
    return "- " + ", ".join(parts) if parts else ""


def _week_section(template, day_docs, start_date):
    lines = ["## This week", ""]
    defaults = {"wake": template["wake"], "sleep": template["sleep"]}
    for offset in range(7):
        date = start_date + datetime.timedelta(days=offset)
        date_str = date.isoformat()
        dow = DOW[date.weekday()]
        day_doc = day_docs.get(date_str)
        branch = (day_doc or {}).get("branch")
        heading = f"### {SHORT_NAME[dow]} {date_str}"
        if template["days"][dow].get("branching"):
            heading += f" (Branch {branch or 'A'})"
        lines.append(heading)
        lines.append("")
        lines.extend(_block_line(b) for b in resolve_blocks(template, dow, branch, day_doc))
        if day_doc:
            override = render_override_line(day_doc, defaults)
            if override:
                lines.append(override)
        lines.append("")
    return lines


def _todo_line(todo):
    """One todo as a markdown task item. Pinned items are bold."""
    box = "x" if todo.get("done") else " "
    text = todo.get("text", "")
    label = f"**{text}**" if todo.get("pinned") else text
    due = todo.get("due")
    return f"- [{box}] {label} (due {due})" if due else f"- [{box}] {label}"


def _todos_section(todos, start_date):
    """Open items, then items completed in the seven days ending start_date.

    The completed window looks backward while the week section looks forward.
    That is deliberate: a record of what actually got done is necessarily about
    the past, and a forward window would almost never contain anything.
    """
    cutoff = (start_date - datetime.timedelta(days=6)).isoformat()

    open_items = [t for t in todos if not t.get("done")]
    recent_done = [
        t for t in todos
        if t.get("done") and (t.get("doneAt") or "")[:10] >= cutoff
    ]

    if not open_items and not recent_done:
        return []

    # Pinned first, then dated soonest first, then undated. Mirrors sortOpen in
    # src/todos.js; kept in step by the shared expectations in the tests rather
    # than by shared code, since the app and the exporter are different runtimes.
    open_items.sort(key=lambda t: (
        0 if t.get("pinned") else 1,
        0 if t.get("due") else 1,
        t.get("due") or "",
        t.get("_id", ""),
    ))
    recent_done.sort(key=lambda t: t.get("doneAt") or "", reverse=True)

    lines = ["## Todos", ""]
    lines.extend(_todo_line(t) for t in open_items)
    lines.extend(_todo_line(t) for t in recent_done)
    lines.append("")
    return lines


def render(template, day_docs, start_date, generated_at, todos=()):
    """Return the whole note. day_docs maps "YYYY-MM-DD" to that day's document."""
    lines = [
        "# Schedule",
        "",
        GENERATED_MARKER,
        f"{_STAMP_PREFIX} {generated_at.isoformat(timespec='seconds')}",
        "",
    ]
    lines.extend(_todos_section(list(todos), start_date))
    lines.extend(_template_section(template))
    lines.extend(_week_section(template, day_docs, start_date))
    return "\n".join(lines).rstrip() + "\n"


def comparable(text):
    """The note with its timestamp removed, for change detection.

    Without this the file differs on every single run by construction, so the
    script would rewrite the note daily and churn the vault's sync history while
    carrying no new information.
    """
    kept = [l for l in text.splitlines() if not l.startswith(_STAMP_PREFIX)]
    return "\n".join(kept)
