"""Build docs/work/index.html: the portfolio page without contact details, for Upwork.

Upwork bars sharing ways to contact a freelancer off-platform before a contract, so
the page linked from Upwork drops the Email and LinkedIn links and points the footer
at Upwork messages. Everything else is the main page, generated from it, so there is
only one page to maintain.

    py tools/build_work_page.py          # write docs/work/index.html
    py tools/build_work_page.py --check  # exit 1 if the committed copy is stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "index.html"
TARGET = ROOT / "docs" / "work" / "index.html"

# Edits as regex patterns (no literal address, so the publish gate stays quiet),
# each required to match exactly once. If the main page's markup changes, the
# build fails here instead of silently shipping a copy with contacts.
EDITS = [
    (r'      <a href="mailto:[^"]+">Email</a>\n', ""),
    (r'      <a href="https://linkedin\.com/[^"]+">LinkedIn</a>\n', ""),
    (r'    <p>To talk about a project, email <a href="mailto:[^"]+">[^<]+</a>'
     r' or message me on <a href="https://linkedin\.com/[^"]+">LinkedIn</a>\.</p>',
     "    <p>To talk about a project, message me here on Upwork.</p>"),
    (r"<head>\n", '<head>\n<meta name="robots" content="noindex">\n'),
]

# Anything that would let a viewer contact the user outside Upwork.
CONTACT_MARKERS = ["mailto:", "jhuraldhilary", "linkedin.com", "+63"]

BANNER = "<!-- Generated by tools/build_work_page.py from docs/index.html. Do not edit by hand. -->\n"


def build(source: str) -> str:
    html = source.replace("\r\n", "\n")
    for pattern, new in EDITS:
        html, count = re.subn(pattern, lambda _m: new, html)
        if count != 1:
            raise ValueError(f"expected exactly one match, found {count}: {pattern.strip()[:60]!r}")
    # The copy lives one folder down, so relative links need to climb back up.
    html = re.sub(r'(href|src)="(?!https?:|mailto:|#|/|\.\./)([^"]+)"', r'\1="../\2"', html)
    html = html.replace("<!doctype html>\n", "<!doctype html>\n" + BANNER, 1)
    leaks = [m for m in CONTACT_MARKERS if m in html]
    if leaks:
        raise ValueError(f"contact details left in the work page: {leaks}")
    return html


def main() -> int:
    built = build(SOURCE.read_text(encoding="utf-8"))
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") if TARGET.exists() else ""
        if current != built:
            print("docs/work/index.html is stale: run py tools/build_work_page.py")
            return 1
        print("docs/work/index.html is current")
        return 0
    TARGET.parent.mkdir(exist_ok=True)
    TARGET.write_text(built, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
